apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todo-namespace
resources:
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/daily-todo.yaml
  - manifests/image-volume-claim.yaml
  - manifests/postgres-config.yaml
  - manifests/postgres.yaml
  - manifests/ingress.yaml
images:
  - name: gcr.io/PROJECT/BACKEND
    newName: thesamsai/todo-app
  - name: gcr.io/PROJECT/DAILY
    newName: thesamsai/daily-todo
secretGenerator:
- name: postgres-password
  envs:
  - .env.secret
